import React, { useState, useEffect } from 'react';
import { Music, Gamepad2, Monitor, Video } from 'lucide-react';
import { motion } from 'framer-motion';

const SJVWBWHWebsite = () => {
  const [language, setLanguage] = useState('zh');

  const translations = {
    zh: {
      title: '欢迎来到SJVWBWH社区',
      modCard: {
        title: 'Minecraft Mod',
        description: '探索我的世界模组',
        button: '立即访问'
      },
      douyinCard: {
        title: '抖音主页',
        description: '关注我的抖音账号',
        button: '立即访问'
      },
      snakeCard: {
        title: '贪吃蛇游戏',
        description: '经典怀旧小游戏',
        button: '立即访问'
      },
      footer: 'created by coze space | 页面内容均由AI生成，仅供参考'
    },
    en: {
      title: 'Welcome to SJVWBWH Community',
      modCard: {
        title: 'Minecraft Mod',
        description: 'Explore Minecraft mods',
        button: 'Visit Now'
      },
      douyinCard: {
        title: 'Douyin Profile',
        description: 'Follow my Douyin account',
        button: 'Visit Now'
      },
      snakeCard: {
        title: 'Snake Game',
        description: 'Classic retro game',
        button: 'Visit Now'
      },
      footer: 'created by coze space | All content generated by AI for reference only'
    }
  };

  useEffect(() => {
    const savedLang = localStorage.getItem('sjvwbwh-lang');
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  const toggleLanguage = () => {
    const newLang = language === 'zh' ? 'en' : 'zh';
    setLanguage(newLang);
    localStorage.setItem('sjvwbwh-lang', newLang);
  };

  const t = translations[language];

  return (
    <div className="min-h-screen bg-[#f8faff] font-sans">
      <header className="sticky top-0 z-50 bg-white shadow-sm">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <h1 className="text-2xl md:text-3xl font-bold text-[#2d3748]">SJVWBWH</h1>
          <button 
            onClick={toggleLanguage}
            className="text-[#4a5568] hover:text-[#2d3748] transition-colors"
          >
            {language === 'zh' ? 'EN' : '中'}
          </button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <h2 className="text-2xl md:text-3xl font-bold text-center text-[#2d3748] mb-8">
          {t.title}
        </h2>

        <div className="flex flex-col lg:flex-row gap-8">
          <div className="flex-1 space-y-6">
            <motion.div
              whileHover={{ y: -2 }}
              whileTap={{ scale: 0.98 }}
              onClick={() => window.open('https://modrinth.com/mod/swhmod', '_blank')}
              className="bg-white rounded-lg shadow-md p-6 cursor-pointer transition-all hover:shadow-lg"
            >
              <div className="flex items-center gap-4">
                <div className="p-3 bg-blue-100 rounded-full text-blue-600">
                  <Monitor size={24} />
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-[#2d3748]">{t.modCard.title}</h3>
                  <p className="text-[#718096]">{t.modCard.description}</p>
                </div>
              </div>
              <div className="mt-4 flex justify-end">
                <button className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors">
                  {t.modCard.button}
                </button>
              </div>
            </motion.div>

            <motion.div
              whileHover={{ y: -2 }}
              whileTap={{ scale: 0.98 }}
              onClick={() => window.open('https://www.douyin.com/user/MS4wLjABAAAAIX6Yze_Yyd3iKui1PdJzuEc23EsoDq02RyG96gJFTjmi-L3K-8BppRZNrnCo13Vi?enter_from=general_search&enter_method=general_search&extra_params=%7B%22search_params%22%3A%7B%22search_result_id%22%3A%224064233830746157%22%2C%22relation_tag%22%3A0%2C%22log_pb%22%3A%7B%22impr_id%22%3A%222025050109400535F12855D95A31F0D3B4%22%7D%2C%22search_type%22%3A%22general%22%2C%22impr_id%22%3A%222025050109400535F12855D95A31F0D3B4%22%2C%22search_id%22%3A%222025050109400535F12855D95A31F0D3B4%22%2C%22search_keyword%22%3A%22sjvwbwh%22%2C%22token_type%22%3A%22discover_list%22%7D%7D&from_tab_name=main', '_blank')}
              className="bg-white rounded-lg shadow-md p-6 cursor-pointer transition-all hover:shadow-lg"
            >
              <div className="flex items-center gap-4">
                <div className="p-3 bg-red-100 rounded-full text-red-600">
                  <Video size={24} />
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-[#2d3748]">{t.douyinCard.title}</h3>
                  <p className="text-[#718096]">{t.douyinCard.description}</p>
                </div>
              </div>
              <div className="mt-4 flex justify-end">
                <button className="px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-600 transition-colors">
                  {t.douyinCard.button}
                </button>
              </div>
            </motion.div>

            <motion.div
              whileHover={{ y: -2 }}
              whileTap={{ scale: 0.98 }}
              onClick={() => window.open('https://snake.org.cn/', '_blank')}
              className="bg-white rounded-lg shadow-md p-6 cursor-pointer transition-all hover:shadow-lg"
            >
              <div className="flex items-center gap-4">
                <div className="p-3 bg-green-100 rounded-full text-green-600">
                  <Gamepad2 size={24} />
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-[#2d3748]">{t.snakeCard.title}</h3>
                  <p className="text-[#718096]">{t.snakeCard.description}</p>
                </div>
              </div>
              <div className="mt-4 flex justify-end">
                <button className="px-4 py-2 bg-green-500 text-white rounded-md hover:bg-green-600 transition-colors">
                  {t.snakeCard.button}
                </button>
              </div>
            </motion.div>
          </div>

          <div className="lg:w-1/3">
            <div className="bg-white rounded-lg shadow-md p-4">
              <div className="flex items-center gap-2 mb-4">
                <Music size={20} className="text-blue-500" />
                <h3 className="text-lg font-semibold text-[#2d3748]">
                  {language === 'zh' ? '音乐播放器' : 'Music Player'}
                </h3>
              </div>
              <iframe 
                frameBorder="no" 
                border="0" 
                marginWidth="0" 
                marginHeight="0" 
                width="100%" 
                height="450" 
                src="//music.163.com/outchain/player?type=1&id=3428868&auto=1&height=430"
              ></iframe>
            </div>
          </div>
        </div>
      </main>

      <footer className="border-t border-[#e2e8f0] py-8 mt-12">
        <div className="container mx-auto px-4 text-center text-[#718096] text-sm">
          <p>
            {t.footer.split('|')[0]} |{' '}
            <a 
              href="https://space.coze.cn" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-blue-500 hover:text-blue-600"
            >
              coze space
            </a>{' '}
            {t.footer.split('|')[1]}
          </p>
        </div>
      </footer>
    </div>
  );
};

export default SJVWBWHWebsite;